create table public.categories (
  id integer generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  sort_order integer not null,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.colors (
  id integer generated by default as identity primary key,
  khmer_name text,
  english_name text not null,
  hex text not null,
  normalized_key text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id integer generated by default as identity primary key,
  slug text not null unique,
  cleaned_code text not null unique,
  display_name text,
  category_id integer references public.categories(id) on delete set null,
  category_source text not null default 'unassigned' check (category_source in ('rule', 'manual', 'unassigned')),
  is_published boolean not null default true,
  is_removed_from_latest_import boolean not null default false,
  review_status text not null default 'clean' check (review_status in ('clean', 'needs_review', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.imports (
  id integer generated by default as identity primary key,
  original_filename text not null,
  digest text not null,
  status text not null check (status in ('preview', 'applied', 'failed', 'rolled_back')),
  parsed_rows integer not null default 0,
  summary_json jsonb,
  validation_json jsonb,
  applied_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.variants (
  id integer generated by default as identity primary key,
  product_id integer not null references public.products(id) on delete cascade,
  color_id integer references public.colors(id) on delete set null,
  pos_code text not null unique,
  size text,
  price numeric(10,2) not null,
  stock_quantity integer not null,
  is_visible boolean not null default true,
  last_seen_import_id integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_media (
  id integer generated by default as identity primary key,
  product_id integer not null references public.products(id) on delete cascade,
  variant_id integer references public.variants(id) on delete set null,
  cloudinary_public_id text not null unique,
  optimized_url text not null,
  alt_text text,
  color_tag text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.import_changes (
  id integer generated by default as identity primary key,
  import_id integer not null references public.imports(id) on delete cascade,
  product_id integer references public.products(id) on delete set null,
  variant_id integer references public.variants(id) on delete set null,
  pos_code text,
  change_type text not null check (change_type in ('new_product', 'new_variant', 'stock_price_update', 'missing_from_import', 'needs_review')),
  before_json jsonb,
  after_json jsonb,
  review_status text not null default 'pending' check (review_status in ('pending', 'accepted', 'ignored')),
  created_at timestamptz not null default now()
);

create table public.store_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);
create index variants_product_id_idx on public.variants(product_id);
create index variants_color_id_idx on public.variants(color_id);
create index product_media_product_id_idx on public.product_media(product_id);
create index product_media_variant_id_idx on public.product_media(variant_id);
create index import_changes_import_id_idx on public.import_changes(import_id);

alter table public.categories enable row level security;
alter table public.colors enable row level security;
alter table public.products enable row level security;
alter table public.imports enable row level security;
alter table public.variants enable row level security;
alter table public.product_media enable row level security;
alter table public.import_changes enable row level security;
alter table public.store_settings enable row level security;
alter table public.admin_profiles enable row level security;
